---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# analysistools

<!-- badges: start -->
<!-- badges: end -->

The goal of analysistools is to help cleaning and analysing survey data.

## Installation

You can install analysistools with:

``` r
install.packages("path/to/analysistools.zip")
```

## Examples

These are some basic examples which shows you how to solve common problems:

```{r example}
library(dplyr)
library(analysistools)

# round2() rounds to nearest, rather than to "even" as round() (IEEE / IEC rounding) does.

a <- seq(-3.5, 3.5, 1)
round(a)
round2(a)

round2(1234, -2)
round2(1234.5678, 1)

b <- seq(1, 100, 1)
wt <- rep(1, 100)
wtd.median(b, weights = wt)

c <- seq(1, 10, 1)
d <- rep(c(0, 1), 3)
getrollingmean(c, 3)
getrollingmean(d, 2)

getrollingtotal(c, 3)
getrollingtotal(d, 2)

iris %>% 
  dplyr::group_by(Species) %>% 
  dplyr::mutate(sepal_length_deciles = getdeciles(Sepal.Length)) %>% 
  dplyr::count(sepal_length_deciles)

e <- c(rep(NA, 50), rep(1, 50))
getdeciles(b, weights = e)


```
